version: '3.9'

services:
  #  Mongoose Container Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #  Node Container Service
  api:
    build: .
    ports:
      - 4040:4040
    environment:
      MONGOOSE_URI: mongodb+srv://ak722872:Hello@World@Mongo@123@ecommerce.z4cbg0g.mongodb.net/?retryWrites=true&w=majority&appName=ECommerce
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}    
    